name: PlayerKitsAddon
main: com.github.neapovil.playerkitsaddon.PlayerKitsAddon
version: 1.0.0
api-version: 1.13
author: Neapovil
website: https://github.com/neapovil/playerkitsaddon
depend:
  - PlayerKits
